ALTER TABLE "drivers" ADD COLUMN "deleted_at"  TIMESTAMP;
ALTER TABLE "drivers" ADD COLUMN "updated_at"  TIMESTAMP;
ALTER TABLE "devices" ADD COLUMN "created_at"  TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "devices" ADD COLUMN "updated_at"  TIMESTAMP DEFAULT CURRENT_TIMESTAMP;