CREATE TABLE IF NOT EXISTS drivers(
    id VARCHAR(255) PRIMARY KEY,
    phone VARCHAR(12) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
