package flespi

type GetDevicesInfo struct {
	Result []struct {
		MessagesTTL   int    `json:"messages_ttl"`
		ProtocolID    int    `json:"protocol_id"`
		DeviceTypeID  int    `json:"device_type_id"`
		ID            int    `json:"id"`
		MediaTTL      int    `json:"media_ttl"`
		Name          string `json:"name"`
		Configuration struct {
			Ident           string `json:"ident"`
			SettingsPolling string `json:"settings_polling"`
		} `json:"configuration"`
		Cid            int `json:"cid"`
		MediaRotate    int `json:"media_rotate"`
		MessagesRotate int `json:"messages_rotate"`
	} `json:"result"`
}

type AutoGenerated struct {
	Result []struct {
		ID        int `json:"id"`
		Telemetry struct {
			Din struct {
				Ts    int `json:"ts"`
				Value int `json:"value"`
			} `json:"din"`
			Position struct {
				Ts    int `json:"ts"`
				Value struct {
					Altitude   int     `json:"altitude"`
					Direction  int     `json:"direction"`
					Hdop       float64 `json:"hdop"`
					Latitude   float64 `json:"latitude"`
					Longitude  float64 `json:"longitude"`
					Satellites int     `json:"satellites"`
					Speed      int     `json:"speed"`
					Valid      bool    `json:"valid"`
				} `json:"value"`
			} `json:"position"`
		} `json:"telemetry"`
	} `json:"result"`
}
